-- ============================================================
-- 电力交易智能辅助决策系统（PTIDSS）DDL 基线 v1.0
-- 枚举值字典（全库 CHECK 约束集中参照，开发/测试/验收共用）
-- 配套：01_postgres_schema.sql（字段级 CHECK）｜数据字典 V1.1
-- 约定：本文件为字典性质，不实际建表；枚举值以 01 脚本 CHECK 为准，
--       本文件仅集中罗列便于检索，防止枚举漂移（评审问题 1 处置）。
-- ============================================================

-- ── 一、市场与交易 ──────────────────────────────────────────
-- 市场类型 market_type        : intra_province 省内 / inter_province 省间
-- 交易阶段 stage              : day_ahead 日前 / real_time 实时 / rolling 滚动
-- 交易品种 variety(contract)  : annual 年度 / monthly 月度 / intra_month 月内 / rolling 滚动
-- 交易品种 variety(midlong)   : annual / monthly / intra_month / rolling / transfer 转让
-- 买卖方向 direction          : buy 买入 / sell 卖出
-- 申报状态 declaration.status : draft / pending_submit / submitted / receipted / partially_matched
-- 成交状态 trade_result.status: matched 全部成交 / partially 部分成交 / unmatched 未成交
-- 方案情景 scenario           : baseline 基准 / conservative 保守 / aggressive 激进
-- 方案类型 plan_type(rolling) : rolling_adjust 滚动调整 / quote_plan 报价方案
-- 方案状态 rolling_plan.status: generated / confirmed / modified / rejected / executed
-- 报价状态 quote_plan.status  : generated / confirmed / submitted
-- 出清来源 clearing_result    : exchange 交易中心 / manual 人工
-- 求解器 solver               : HiGHS / SCIP / Gurobi（HiGHS 开源默认，Gurobi 兜底）
-- 优化状态 joint_optim.status : queued / running / success / suboptimal / failed

-- ── 二、发电与负荷 ──────────────────────────────────────────
-- 电源类型 fuel_type          : thermal 火电 / hydro 水电 / wind 风电 / pv 光伏 / storage 储能
-- 机组状态 plant_unit.status  : active 运行 / retired 退役 / under_construction 在建
-- 检修类型 maintenance_plan   : planned 计划检修 / unplanned 非计划
-- 气象源 weather.source      : GFS / ECMWF / CMA

-- ── 三、结算 ────────────────────────────────────────────────
-- 结算来源 settlement_record  : system 系统 / exchange 交易中心
-- 同步状态 sync_status        : synced / pending / diff
-- 核对状态 reconcile.status   : consistent 一致 / diff 差异 / pending 待核对
-- 工单类型 ticket.diff_type   : amount_diff 金额差异 / missing_record 缺记录 / extra_record 多记录
-- 工单状态 ticket.status      : pending / processing / reviewed / closed
-- 台账状态 ledger.status      : opened 开账 / confirmed 确认 / closed 关账
-- OCR 状态 ocr_task.status    : pending / recognizing / success / low_confidence / failed
-- OCR 复核 review_status      : not_required / pending / reviewed
-- 模板状态 ocr_template.status: learning / active / disabled

-- ── 四、政策与规则 ──────────────────────────────────────────
-- 政策分类 policy_document    : national 国家 / regional 区域 / provincial 省级
-- 条款类型 policy_article     : trade_rule 交易规则 / price_mechanism 价格机制 / assessment 考核 / settlement 结算
-- 影响环节 policy_analysis    : 预测 / 决策 / 申报 / 结算 / 考核
-- 影响程度 impact_level       : high / medium / low
-- 规则类型 rule_config        : compliance 合规 / decision 决策 / assessment 考核
-- 规则状态 rule_config.status : draft / active / expired

-- ── 五、预测与模型 ──────────────────────────────────────────
-- 预测模型 model_code         : generation 出力 / price 价格 / load 负荷
-- 任务状态 forecast_task      : queued / running / success / failed / degraded 降级
-- 模型框架 model_registry     : pytorch / xgboost / lightgbm
-- 模型状态 model_registry     : training / evaluating / online / rolled_back
-- 训练触发 training_task      : daily_increment 日增量 / weekly_full 周全量 / manual 手动

-- ── 六、决策与智能体 ────────────────────────────────────────
-- 智能体编码 agent_code       : forecast 预测 / market 行情 / quote 报价 / risk 风险
--                              / compliance 合规 / settlement 结算 / review 复盘
-- 智能体状态 agent_registry   : active / disabled / maintenance
-- 运行状态 agent_run          : success / failed / timeout
-- 会话类型 decision_session   : rolling 滚动 / spot_quote 现货报价 / joint_optimize 联合优化
-- 人审状态 human_review       : pending / confirmed / modified / rejected
-- 回测状态 backtest_run       : running / success / failed
-- 策略状态 strategy_library   : effective / invalid / evaluating
-- 策略来源 strategy_library   : backtest 回测 / review 复盘 / manual 人工

-- ── 七、复盘与考核 ──────────────────────────────────────────
-- 报告类型 review_report      : weekly 周报 / monthly 月报 / special 专题
-- 归因层 deviation_record     : forecast 预测 / decision 决策 / execution 执行
-- 偏差方向 direction          : positive 正向 / negative 负向
-- 回流结论 strategy_feedback  : effective / invalid / adjust
-- 指标状态 assess_indicator   : active / disabled
-- 考核范围 assess_result      : personal 个人 / team 团队
-- 考核状态 assess_result      : pending / confirmed / appealing / corrected
-- 申诉状态 assess_appeal      : pending / processing / approved / rejected

-- ── 八、报表 ────────────────────────────────────────────────
-- 报表类型 report_template    : trade 交易 / settlement 结算 / forecast 预测
--                              / assessment 考核 / business 经营
-- 周期类型 period_type        : daily / weekly / monthly / yearly
-- 生成状态 report_instance    : pending / generating / success / failed
-- 推送状态 push_status        : none / pushed

-- ── 九、平台 ────────────────────────────────────────────────
-- 角色编码 sys_role.role_code : trader 交易员 / analyst 分析师 / settlement 结算员
--                              / admin 管理员 / manager 经理 / compliance 合规 / mobile 移动审批
-- 资源类型 sys_permission     : menu 菜单 / api 接口 / data 数据
-- 用户状态 sys_user.status    : active / locked / disabled
-- 审计结果 audit_log.result   : success / fail
-- 消息类型 message_record     : forecast_summary / market_alert / decision_todo
--                              / settlement_diff / assess_reminder / approval_task 审批任务（评审决议④）
--                              / intel_push 情报推送（V1.7，biz_ref=INTEL-{newsId} 幂等）
-- 消息渠道 message.channel    : web / miniapp（JSONB 数组）
-- 区域状态 sys_region.status  : enabled / disabled / pending 待接入
-- 通道配置 sys_region         : rest / sftp / both（评审决议①）
-- 结算口径 sys_region         : natural_month 自然月 / trading_month 交易月（评审决议③）

-- ── 十、数据管理与情报 ──────────────────────────────────────
-- 数据源类型 data_source      : marketing 营销 / exchange 交易中心 / weather 气象 / file 文件 / intel 情报
-- 同步模式 sync_mode          : realtime 实时 / timed 定时
-- 数据源状态 data_source      : enabled / disabled / error
-- 采集类型 collect_task       : market / trade / settlement / weather / intel
-- 质量规则 data_quality_rule  : completeness 完整性 / accuracy 准确性 / timeliness 及时性
-- 严重级别 severity           : high / medium / low
-- 血缘节点 data_lineage       : table / task / report / model
-- 情报类型 intel_source       : price 价格 / weather 气象 / supply_demand 供需 / policy 政策
--                              / announcement 公告 / opinion 观点
-- 获取方式 fetch_mode         : api / crawl / file
-- 情报重要度 intel_news       : high / medium / low
-- 推送状态 intel_news         : none / pushed
-- 推送规则 intel_push_rule    : 状态 active / disabled；重要度过滤 high / medium / low（V1.7）

-- ============================================================
-- 使用方式：本文件为枚举参照字典，供 SQL 开发、数据校验、测试造数与
-- 验收核对使用；枚举变更须同步修改 01 脚本 CHECK 与本字典（版本化）。
-- ============================================================
