<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>low-code</artifactId>
        <groupId>com.troy</groupId>
        <version>1.0.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>low-code-modules</artifactId>
    <packaging>pom</packaging>

    <description>
        low-code-modules业务模块
    </description>

    <modules>
        <module>low-code-modules-system</module>
        <module>low-code-modules-gen</module>
        <module>low-code-modules-job</module>
        <module>low-code-modules-file</module>
        <module>low-code-modules-camunda</module>
        <module>low-code-modules-form</module>
        <module>low-code-modules-sync</module>
        <module>low-code-modules-sync-inside</module>
    </modules>
</project>