spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/ptidss
    username: ptidss
    password: ptidss
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-init-sql: SET app.region_code = ''
